# Mantenemos el puerto y la región
server.port=8080
aws.region=us-east-1

# El nombre de la tabla debe coincidir con la que crees en tu Docker local
aws.productsddb.name=products

# NUEVAS: Estas son las que usará tu Bean de configuración para desviarse a Localhost
aws.dynamodb.endpoint=http://localhost:8000
aws.accessKey=local
aws.secretKey=local

# Logs (opcional, igual que el original)
logging.level.com.amazonaws.xray=ERROR
logging.level.com.root=INFO

# Endpoint unificado de LocalStack
aws.sns.endpoint=http://localhost:4566
aws.sns.topic.name=product-events